name: pretty
version: 0.0.6
author: Paul Brauner <polux@google.com>
description: A sample command-line application
homepage: https://github.com/polux/pretty
dev_dependencies:
  args: any
  enumerators: '>=0.4.2 <0.5.0'
  persistent: '>=0.7.4 <0.8.0'
  propcheck: '>=0.3.5 <0.4.0'
  unittest: any
